export default [
        {
          icon: "mdi-monitor-dashboard",
          titulo: "Relatórios gerenciais",
          code: "rel-gerenciais",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/lista-produtos",
              text: "Lista de Produtos",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/lista-clientes",
              text: "Lista de Clientes",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/lista-movimentacao",
              text: "Lista de Movimentações",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/lista-vendas",
              text: "Lista de Vendas",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
          ],
        },
        {
          icon: "mdi-cart",
          titulo: "Relatórios de Vendas",
          code: "rel-compras",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/compras-clientes",
              text: "Compras por Clientes",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-lojas",
              text: "Compras por Lojas",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-origem",
              text: "Compras por Origem",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
          ]
        },
      ];