export default [
        {
          icon: "mdi-monitor-dashboard",
          titulo: "Relatórios gerenciais",
          code: "rel-gerenciais",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/resumo-gerencial",
              text: "Resumo Gerencial",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ]
            },
            {
              to: "/resumo-auditoria",
              text: "Resumo Auditoria",
              roles: [
                "ADMIN",
                "SUPERVISOR"
              ],
            },
            {
              to: "/resumo-utilizacao",
              text: "Resumo Utilização",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-gerenciais-resumo-inadimplencia",
              text: "Resumo Inadimplência",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-gerenciais-resumo-faturamento",
              text: "Resumo Faturamento",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/perfil-carteira",
              text: "Perfil da Carteira",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/clientes-ativos",
              text: "Clientes Ativos",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/clientes-novos",
              text: "Clientes Novos",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-gerencial-recebiveis-por-vencimento",
              text: "Recebíveis por Vencimento",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/recupera-atrasados-v1",
              text: "Recuperação de Atrasados (Carnê - V1)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/recupera-atrasados-v2",
              text: "Recuperação de Atrasados (Carnê - V2)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/inadimplencia-primeira-fatura",
              text: "Inadimplência na primeira fatura",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },            
            {
              to: "/analise-inadimplencia",
              text: "Análise de Inadimplência",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/demonstrativo-resultado",
              text: "Demostrativo Resultado Por Exercício",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/evolucao-carteira",
              text: "Evolução de carteira",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            }
          ],
        },
        {
          icon: "mdi-cart",
          titulo: "Relatórios de compras",
          code: "rel-compras",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/compras-clientes",
              text: "Compras por Clientes",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-lojas",
              text: "Compras por Lojas",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-origem",
              text: "Compras por Origem",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-perfil",
              text: "Compras por Perfil Cliente",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-modalidade",
              text: "Compras por Modalidade",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-vencimento",
              text: "Compras por Vencimento",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-ramo",
              text: "Compras por Ramo de Atividade",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-tipo-transacao",
              text: "Compras por tipo de transação",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-parcelas",
              text: "Compras por Parcelas(Carnês)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/idas-a-loja",
              text: "Compras por Idas à Loja",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-canceladas",
              text: "Compras Canceladas",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-recusadas-sintetico",
              text: "Recusadas Sintético",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/compras-recusadas-analitico",
              text: "Recusadas Analítico",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/duplicidade",
              text: "Duplicidade de Autorizações",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            // {
            //   to: "/repique-loja",
            //   text: "Repique Loja",
            //   roles: [
            //     "ADMIN",
            //     "SUPERVISOR",
            //     "COMERCIAL",
            //     "NEGOCIADOR",
            //     "PROPRIETARIO",
            //     "PROPRIETARIO_RELATORIO",
            //     "CREDIARISTA",
            //   ],
            // },
            {
              to: "/recompra-loja",
              text: "Recompra Loja",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
          ],
        },
        {
          icon: "mdi-credit-card-outline",
          titulo: "Relatórios pagamentos",
          code: "rel-pagamentos",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/pag-clientes",
              text: "Pagamento de Clientes",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/pag-local",
              text: "Pagamento por Local",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
          ],
        },
        {
          icon: "mdi-card-account-details",
          titulo: "Relatórios clientes",
          code: "rel-clientes",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/rel-clientes",
              text: "Relação de Clientes",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/clientes-atraso",
              text: "Clientes em Atraso",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/limite-disponivel",
              text: "Limite Disponível por Cliente",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-consulta-spc",
              text: "Consultas no SPC (Analítico)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/resumo-consulta-spc",
              text: "Consultas no SPC (Resumo)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/docs-armazenados",
              text: "Documentos Armazenados",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/proposta-adesao",
              text: "Proposta de Adesão",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "PROPRIETARIO",
              ],
            },
            {
              to: "/rel-comprovante-quitacao",
              text: "Declaração Anual de Quitação",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "PROPRIETARIO",
              ],
            },
          ],
        },
        {
          icon: "mdi-headset",
          titulo: "Relatórios cobrança",
          code: "rel-cobranca",
          roles: [
            "ADMIN", 
            "SUPERVISOR", 
            "COMERCIAL", 
            "NEGOCIADOR"
          ],
          lista: [
            {
              to: "/acordos-efetuados",
              text: "Acordos Efetuados e Acordos em atraso",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/cobranca-por-usuario-analitico",
              text: "Cobrança por Usuário (Analítico)",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/cobranca-por-usuario-sintetico",
              text: "Cobrança por Usuário (Sintético)",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/ultimas-cobrancas",
              text: "Últimas Cobranças",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/rel-cliente-sem-cobranca",
              text: "Clientes sem cobrança ",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/cobranca-retorno-por-usuario",
              text: "Retorno por Usuário",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
            {
              to: "/defas-cobranca",
              text: "Defasagem Cobrança",
              roles: [
                "ADMIN", 
                "SUPERVISOR", 
                "COMERCIAL", 
                "NEGOCIADOR"
              ],
            },
          ],
        },
        {
          icon: "mdi-chart-histogram",
          titulo: "Relatórios movimento",
          code: "rel-movimento",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/mov-compras",
              text: "Movimento de Compras",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/mov-pagamentos",
              text: "Movimento de Pagamentos",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/mov-loja",
              text: "Movimento por Loja",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/mov-retornos-banco",
              text: "Movimento de Retornos do banco",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/mov-cobranca-registrada-analitico",
              text: "Movimento de Cobrança Registrada (Analítico)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/mov-cobranca-registrada-sintetico",
              text: "Movimento de Cobrança Registrada (Sintético)",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
          ],
        },
        {
          icon: "mdi-bank-transfer",
          titulo: "Relatórios repasse",
          code: "rel-repasse",
          roles: [
            "ADMIN",
            "SUPERVISOR",
            "COMERCIAL",
            "NEGOCIADOR",
            "PROPRIETARIO",
            "PROPRIETARIO_RELATORIO",
            "CREDIARISTA",
          ],
          lista: [
            {
              to: "/rel-repasse-lancamentos",
              text: "Repasse de Lançamentos Analíticos",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-repasse-lancamento-extra",
              text: "Repasse Lançamento Extra",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-repasse-previsao-pagamento",
              text: "Repasse Previsão de Pagto",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-repasse-pagamento-efetuado",
              text: "Repasse Pagto Efetuado",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/rel-repasse-resumo-pagto",
              text: "Repasse Resumo de Pagto",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "PROPRIETARIO_RELATORIO",
                "CREDIARISTA",
              ],
            },
          ],
        },
        {
          icon: "mdi-calendar",
          titulo: "Relatórios Redes e Lojas",
          code: "rel-redes-lojas",
          roles: ["ADMIN", "SUPERVISOR", "COMERCIAL", "NEGOCIADOR"],
          lista: [
            {
              to: "/lojas-credenciadas",
              text: "Lojas credenciadas",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
            {
              to: "/empresas-lojas",
              text: "Empresas / Lojas",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR"
              ],
            },
            {
              to: "/rel-tarifa-por-loja",
              text: "Tarifa por loja",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR"
              ],
            },
            {
              to: "/tarifa-por-rede",
              text: "Tarifa por rede",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR"
              ],
            },
          ],
        },
        {
          icon: "mdi-cog",
          titulo: "Relatórios sistema",
          code: "rel-sistema",
          roles: ["ADMIN", "SUPERVISOR", "COMERCIAL", "NEGOCIADOR"],
          lista: [
            {
              to: "/rel-usuario",
              text: "Relação de Usuários",
              roles: [
                "ADMIN",
                "SUPERVISOR",
                "COMERCIAL",
                "NEGOCIADOR",
                "PROPRIETARIO",
                "CREDIARISTA",
              ],
            },
          ],
        },
      ];